name: Run Graph Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Entra ID Workload Identity Federation'
      uses: nicolonsky/WIF@v0.0.2
      with:
          client_id: ${{ secrets.GRAPH_CLIENT_ID }}
          tenant_id: ${{ secrets.GRAPH_TENANT_ID }}
          # OIDC audience, # optional, default is api://AzureADTokenExchange
          audience: api://AzureADTokenExchange
          # OIDC Scope, # optional, default is https://graph.microsoft.com/.default
          scope: https://graph.microsoft.com/.default
          
  
